import Head from 'next/head'
import { createContext } from 'react';
import Header from './Header';

export const appContext=createContext();

const Layout = (props) => {
    return (
        <appContext.Provider value={props.headerMenu}>
            <div>
                <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
                </Head>
                <div className='container'>
                    <Header></Header>
                    {props.children}
                </div>
            </div>
            </appContext.Provider>
    );
};

export default Layout;